### ISSUE TITLE
Texts for FAQ

### ISSUE THREAD

**Issue by CalamariFritti** [lakeside213/FindMyFilm#1]
Hey guys,
thanks for your work with providing the materials for the website. 

I just pushed the first couple of pages (no movie content yet, though). 
I have only a small question regarding texts: There were FAQ questions or did i just not see them? 
So i just build the faq page with placeholder elements for the questions, same with the about us page.
I added some short paragraph additional to business description and mission.

I will push the first movie pages hopefully soon.

**Comment by lekankoku** [comment]
How to download the movie?
The movie would be found on the official website of the particular movie and based on their policy either you buy or free download it.

Is every movie available here free?
No, the website especially deals with providing you information on the requirements to view the movies with their ratings. For further information visit the official site of the movie. And for your information, most of the movies are not free to download.

**Comment by CalamariFritti** [comment]
These quetions have been added and also one additional question regarding signing up.
Thank you.
