### ISSUE TITLE
GitHub pages

### ISSUE THREAD

**Issue by CalamariFritti** [lakeside213/FindMyFilm#2]
Hello,
the website should be complete now. I did a bit more work now and added all the listing and single movie pages that were mentioned (so, not only the pages required from the list). Everything works on my side using FireFox(93.0 on 64-bit) and Chrome.

I am not sure if you set up this repo as a github pages project? If not could you please do this? Thank you and good night.

**Comment by lekankoku** [comment]
Heres the github pages link
https://lakeside213.github.io/FindMyFilm/assignment-2b/index.html
